
CREATE TABLE TB_CLASS(
CLASS_NO NUMBER(6) NOT NULL,
TEACHER_NO NUMBER(6) NOT NULL,
CLASS_NAME VARCHAR2(100) NOT NULL,
CATEGORY_NO NUMBER(6) NOT NULL,
CLASS_REG_DATE DATE NOT NULL,
CLASS_UPDATE_DATE DATE NOT NULL,
CLASS_MEMBER_MAX NUMBER(5) NOT NULL
);

CREATE TABLE TB_TEACHER(
TEACHER_NO NUMBER(6) NOT NULL,
TEACHER_ID VARCHAR2(100) NOT NULL,
TEACHER_NICKNAME VARCHAR2(100) NOT NULL,
TEACHER_EMAIL VARCHAR2(100) NOT NULL,
TEACHER_REG_DATE DATE NOT NULL,
TEACHER_UPDATE_DATE DATE NOT NULL,
TEACHER_PHONE VARCHAR2(15) NOT NULL
);

CREATE TABLE TB_STUDENT_CLASS(
STUDENT_NO NUMBER(6) NOT NULL,
CLASS_NO NUMBER(6) NOT NULL,
TEACHER_NO NUMBER(6) NOT NULL
);
COMMIT;

CREATE TABLE TB_LIKE(
CLASS_NO NUMBER(6) NOT NULL,
STUDENT_NO NUMBER(6) NOT NULL
);

CREATE TABLE TB_CLASS_ADDR_PICK(
ADDR_NO NUMBER(6) NOT NULL,
CLASS_NO NUMBER(6) NOT NULL
);

CREATE TABLE TB_FILE(
FILE_NO NUMBER(6) NOT NULL,
CLASS_NO NUMBER(6) NOT NULL,
FILE_ORIGIN VARCHAR2(100) NOT NULL,
FILE_SAVE VARCHAR2(100) NOT NULL,
FILE_EXTENSION VARCHAR2(100) NOT NULL,
FILE_SIZE VARCHAR2(100) NOT NULL,
FILE_REG_DATE DATE NOT NULL,
FILE_UPDATE_DATE DATE NOT NULL
);

CREATE TABLE TB_TEACHER_CATEGORY(
CATEGORY_NO NUMBER(6) NOT NULL,
TEACHER_NO NUMBER(6) NOT NULL
);

CREATE TABLE TB_CLASS_QNA(
CLASS_QNA_NO NUMBER(6) NOT NULL,
CLASS_NO NUMBER(6) NOT NULL,
TEACHER_NO NUMBER(6) NOT NULL,
CLASS_QNA_CONTENT VARCHAR2(700) NOT NULL,
CLASS_REG_DATE DATE NOT NULL,
CLASS_STUDENT_NO NUMBER(6) NOT NULL,
CLASS_QNA_GROUP_NO NUMBER(6) NOT NULL,
CLASS_QNA_DEPTH NUMBER(1) NOT NULL,
CLASS_QNA_ORIGIN_NO NUMBER(6) NOT NULL
);
COMMIT;


